---
# Source: aws-cloud-controller-manager/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-cloud-controller-manager
  labels:
    k8s-app:  aws-cloud-controller-manager
    helm.sh/chart: "aws-cloud-controller-manager-0.0.7"
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app:  aws-cloud-controller-manager
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: aws-cloud-controller-manager
      labels:
        k8s-app:  aws-cloud-controller-manager
    spec:
      tolerations: 
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
      nodeSelector: 
        node-role.kubernetes.io/control-plane: ""
      dnsPolicy: Default
      priorityClassName: system-node-critical
      serviceAccountName: cloud-controller-manager
      securityContext:
        {}
      containers:
        - name: aws-cloud-controller-manager
          image: "registry.k8s.io/provider-aws/cloud-controller-manager:v1.27.2"
          args:
            - --v=2
            - --cloud-provider=aws
            - --cluster-cidr=10.244.0.0/16    # Added to fix error
            - --allocate-node-cidrs=true      # Added to fix error
            - --configure-cloud-routes=false  # Added to fix error
          resources:
            requests:
              cpu: 200m
          env:
            []
          securityContext:
            {}
