---
# Source: aws-cloud-controller-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
  labels:
    helm.sh/chart: "aws-cloud-controller-manager-0.0.7"
